# Generated by Django 4.2.14 on 2024-07-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_Name',
            new_name='image_name',
        ),
    ]
